### ISSUE TITLE
Cannot find module 'electron-prebuilt'

### ISSUE THREAD

**Issue by Nevon** [olahol/viewdiff#1]
Because `electron-prebuild` is listed as a `devDependency`, `viewdiff` fails to run when installed globally.

![screen shot 2015-10-19 at 11 48 58](https://cloud.githubusercontent.com/assets/83586/10574617/75f72374-7657-11e5-80e1-eb4abb9909c1.png)

```
➜  my-repo git:(master) git diff | viewdiff
module.js:338
    throw err;
    ^

Error: Cannot find module 'electron-prebuilt'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/viewdiff/cli.js:3:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

**Comment by olahol** [comment]
Shit, well that's embarrassing :disappointed:, I've fixed it in `1.0.2` and unpublished `1.0.1` and `1.0.0`. Thank you.
